from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .prompting import artifact_descriptor_for_path


ARTIFACT_SPECS: list[dict[str, Any]] = [
    {
        "path_pattern": "analysis/index.json",
        "kind": "json",
        "produced_by": ["analyze"],
        "description": "Machine-readable project index for queries, diagnostics, resolved SQL, and generated artifacts.",
        "top_level_fields": ["files", "queries", "resolved_queries", "diagnostics", "artifacts", "entrypoint"],
    },
    {
        "path_pattern": "analysis/executive_summary.json",
        "kind": "json",
        "produced_by": ["analyze"],
        "description": "Management summary for analyzer coverage, complexity hotspots, value hotspots, trend, and evolution.",
        "top_level_fields": [
            "generated_at",
            "profile_path",
            "headline",
            "management_summary",
            "trend_summary",
            "complexity_summary",
            "value_summary",
            "diagnostics_summary",
            "evolution_summary",
            "profile_lifecycle",
            "next_actions",
        ],
    },
    {
        "path_pattern": "analysis/failure_clusters.json",
        "kind": "json",
        "produced_by": ["analyze", "prepare-prompt"],
        "description": "Grouped recurring diagnostics with minimal evidence and task types for weak-LLM prompting.",
        "top_level_fields": ["generated_at", "clusters"],
    },
    {
        "path_pattern": "analysis/context_packs/*.json",
        "kind": "json",
        "produced_by": ["compile-context", "run-agent-loop"],
        "description": "Phase-specific context packs compiled for weak 128k-token models and autonomous loop tasks.",
        "top_level_fields": [
            "cluster_id",
            "phase",
            "prompt_profile",
            "estimated_tokens",
            "max_input_tokens",
            "included_artifacts",
            "sections",
            "prompt_text",
        ],
    },
    {
        "path_pattern": "analysis/prompt_packs/*-bundle.json",
        "kind": "json",
        "produced_by": ["analyze", "prepare-prompt"],
        "description": "Prompt bundle metadata for classify/propose/verify stages and expected JSON schemas.",
        "top_level_fields": ["generated_at", "cluster_id", "budget", "model", "stages"],
    },
    {
        "path_pattern": "analysis/llm_runs/*/run_summary.json",
        "kind": "json",
        "produced_by": ["invoke-llm"],
        "description": "Single provider invocation summary with prompt metadata, token limits, usage, and optional review status.",
        "top_level_fields": [
            "generated_at",
            "cluster_id",
            "stage",
            "budget",
            "prompt_model",
            "provider_name",
            "provider_model",
            "token_limit",
            "prompt_estimated_tokens",
            "response_usage",
            "review_enabled",
        ],
    },
    {
        "path_pattern": "analysis/provider_validation/*/summary.json",
        "kind": "json",
        "produced_by": ["validate-provider"],
        "description": "Provider validation summary with pass/fail status, probe checks, troubleshooting hints, and saved artifact paths.",
        "top_level_fields": [
            "generated_at",
            "validation_id",
            "status",
            "provider_name",
            "provider_model",
            "normalized_url",
            "token_limit",
            "checks",
            "error",
            "troubleshooting_hints",
            "debug_path",
        ],
    },
    {
        "path_pattern": "analysis/provider_validation/*/debug.json",
        "kind": "json",
        "produced_by": ["validate-provider"],
        "description": "Detailed provider validation debug payload with config snapshot, request/response paths, and failure classification.",
        "top_level_fields": [
            "generated_at",
            "validation_id",
            "status",
            "input",
            "resolved_config",
            "prompt_preview",
            "checks",
            "error",
            "troubleshooting_hints",
        ],
    },
    {
        "path_pattern": "analysis/llm_reviews/*-review.json",
        "kind": "json",
        "produced_by": ["review-llm-response", "invoke-llm --review"],
        "description": "Weak-LLM review result with schema validation, accepted patch candidate, and next prompt guidance.",
        "top_level_fields": [
            "cluster_id",
            "stage",
            "status",
            "issues",
            "safe_to_apply_candidate",
            "profile_patch_candidate",
            "next_prompt_kind",
        ],
    },
    {
        "path_pattern": "analysis/agent_tasks/*.json",
        "kind": "json",
        "produced_by": ["run-agent-loop", "resume-agent-loop"],
        "description": "Queued Cline-bridge phase tasks written by the autonomous loop for external subagent execution.",
        "top_level_fields": [
            "task_id",
            "phase",
            "cluster_id",
            "runner_mode",
            "model_profile",
            "input_pack_path",
            "expected_schema",
            "attempt",
            "max_attempts",
            "token_budget",
        ],
    },
    {
        "path_pattern": "analysis/agent_runs/*.result.json",
        "kind": "json",
        "produced_by": ["run-agent-loop", "resume-agent-loop"],
        "description": "Normalized autonomous loop runner outputs for provider or Cline-bridge task execution.",
        "top_level_fields": [
            "generated_at",
            "task_id",
            "phase",
            "cluster_id",
            "runner_name",
            "response_text_path",
            "raw_text",
            "structured_output",
            "usage",
        ],
    },
    {
        "path_pattern": "analysis/proposals/rule_proposals.json",
        "kind": "json",
        "produced_by": ["propose-rules"],
        "description": "Accepted weak-LLM patch candidates collected into a proposal bundle for simulation.",
        "top_level_fields": [
            "generated_at",
            "analysis_root",
            "profile_source",
            "summary",
            "accepted_patches",
            "skipped_reviews",
        ],
    },
    {
        "path_pattern": "analysis/proposals/candidate_profile.json",
        "kind": "json",
        "produced_by": ["propose-rules", "apply-profile-patch"],
        "description": "Merged candidate profile ready for simulation, grading, and promotion.",
        "top_level_fields": [
            "profile_version",
            "profile_name",
            "profile_status",
            "parent_profile",
            "reference_target_default_order",
            "reference_token_patterns",
            "external_xml_name_map",
            "external_xml_scoped_map",
            "ignore_tags",
            "rules",
            "validation_history",
            "lifecycle_history",
        ],
    },
    {
        "path_pattern": "validation/profile_validation.json",
        "kind": "json",
        "produced_by": ["validate-profile", "simulate-profile"],
        "description": "Baseline-versus-profile validation payload with delta and recommendation.",
        "top_level_fields": ["profile_path", "assessment", "baseline", "profiled", "delta", "rule_usage"],
    },
    {
        "path_pattern": "simulation/profile_simulation.json",
        "kind": "json",
        "produced_by": ["simulate-profile"],
        "description": "Candidate profile simulation wrapper around the validation payload.",
        "top_level_fields": ["generated_at", "candidate_profile_path", "assessment", "validation_payload"],
    },
    {
        "path_pattern": "grade/profile_grade.json",
        "kind": "json",
        "produced_by": ["grade-profile"],
        "description": "Lifecycle grade with suggested next status, rollback recommendation, and reasoning.",
        "top_level_fields": [
            "generated_at",
            "profile_path",
            "validation_report_path",
            "current_status",
            "suggested_status",
            "promotion_readiness",
            "assessment",
            "history_summary",
            "latest_delta",
            "rollback_recommendation",
            "reasoning",
        ],
    },
    {
        "path_pattern": "profiles/*.history.json",
        "kind": "json",
        "produced_by": ["promote-profile", "rollback-profile"],
        "description": "Lifecycle sidecar summarizing profile validation history and lifecycle events.",
        "top_level_fields": [
            "generated_at",
            "profile_path",
            "profile_name",
            "profile_status",
            "profile_version",
            "parent_profile",
            "validation_history",
            "lifecycle_history",
        ],
    },
    {
        "path_pattern": "analysis/schema/artifact_catalog.json",
        "kind": "json",
        "produced_by": ["analyze"],
        "description": "Catalog of stable artifact contracts for humans, automation, and weaker LLMs.",
        "top_level_fields": ["generated_at", "artifacts"],
    },
    {
        "path_pattern": "analysis/agent_loop/loop_state.json",
        "kind": "json",
        "produced_by": ["run-agent-loop", "resume-agent-loop"],
        "description": "Current autonomous loop state, phase progress, token budget, and stop conditions.",
        "top_level_fields": [
            "run_id",
            "status",
            "current_phase",
            "completed_phases",
            "pending_clusters",
            "active_task_id",
            "iteration_count",
            "required_artifacts",
            "completed_artifacts",
            "stop_reason",
            "last_error",
            "token_budget",
            "config",
            "completed_cluster_stages",
            "cluster_attempts",
            "latest_outputs",
        ],
    },
    {
        "path_pattern": "analysis/agent_loop/completion_report.json",
        "kind": "json",
        "produced_by": ["run-agent-loop", "resume-agent-loop"],
        "description": "Terminal autonomous loop status showing completed versus missing required artifacts.",
        "top_level_fields": [
            "generated_at",
            "run_id",
            "status",
            "iterations",
            "completed_artifacts",
            "missing_artifacts",
            "stop_reason",
            "last_error",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/overview.json",
        "kind": "json",
        "produced_by": ["prepare-java-bff"],
        "description": "Weak-model-friendly overview for generating Java Spring Boot BFF implementation logic against Oracle 19c.",
        "top_level_fields": [
            "generated_at",
            "target_runtime",
            "weak_model_strategy",
            "entry_query_count",
            "bundle_count",
            "bundles",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/chunk_manifest.json",
        "kind": "json",
        "produced_by": ["prepare-java-bff"],
        "description": "Chunk-level token manifest and bundle sequencing for Qwen3-safe Java BFF prompting.",
        "top_level_fields": [
            "generated_at",
            "model_profile",
            "recommended_single_prompt_limit",
            "bundle_count",
            "chunk_count",
            "bundles",
            "chunks",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/implementation_cards/*.json",
        "kind": "json",
        "produced_by": ["prepare-java-bff"],
        "description": "Per-query implementation cards with Oracle 19c SQL logic, Java binding hints, and manual-review flags.",
        "top_level_fields": [
            "query_id",
            "status",
            "parameters",
            "diagnostics",
            "sql_logic",
            "java_bff_logic",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/sql_chunks/*.json",
        "kind": "json",
        "produced_by": ["prepare-java-bff"],
        "description": "Chunked SQL excerpts sized for weak-model repository-phase prompts so large Oracle 19c queries stay under token limits.",
        "top_level_fields": [
            "chunk_id",
            "query_id",
            "sequence",
            "estimated_tokens",
            "start_line",
            "end_line",
            "sql_excerpt",
            "clause_hints",
            "implementation_focus",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/phase_packs/*/*.json",
        "kind": "json",
        "produced_by": ["prepare-java-bff"],
        "description": "Phase-specific prompt payloads for weak LLMs to derive Java Spring Boot BFF implementation logic without exceeding token budgets.",
        "top_level_fields": [
            "generated_at",
            "phase",
            "bundle_id",
            "prompt_profile",
            "estimated_prompt_tokens",
            "budget",
            "recommended_input_artifacts",
            "answer_schema",
            "prompt_text",
            "safe_for_qwen3",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/context_packs/*/*.json",
        "kind": "json",
        "produced_by": ["compile-java-bff-context", "invoke-java-bff", "run-java-bff-loop", "resume-java-bff-loop"],
        "description": "Token-budgeted Java BFF phase context packs compiled for weak 128k-token models such as Qwen3.",
        "top_level_fields": [
            "context_contract_version",
            "phase",
            "bundle_id",
            "phase_pack_path",
            "prompt_profile",
            "budget",
            "estimated_prompt_tokens",
            "safe_for_qwen3",
            "included_artifacts",
            "missing_inputs",
            "answer_schema",
            "prompt_text",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/reviews/*/*-review.json",
        "kind": "json",
        "produced_by": ["review-java-bff-response", "invoke-java-bff --review", "run-java-bff-loop"],
        "description": "Schema-validated Java BFF phase review outputs with merge readiness and repair guidance.",
        "top_level_fields": [
            "generated_at",
            "bundle_id",
            "phase",
            "status",
            "issues",
            "parsed_response",
            "accepted_for_merge",
            "next_phase_pack_path",
            "repair_prompt_path",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/tasks/*/*.json",
        "kind": "json",
        "produced_by": ["run-java-bff-loop", "resume-java-bff-loop"],
        "description": "Cline-bridge task contract for a single Java BFF phase execution with compiled context and schema expectations.",
        "top_level_fields": [
            "task_contract_version",
            "task_id",
            "runner_mode",
            "bundle_id",
            "phase",
            "phase_pack_path",
            "context_pack_path",
            "context_prompt_path",
            "expected_schema",
            "token_budget",
            "missing_inputs",
            "recommended_result_path",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/agent_runs/*/*.result.json",
        "kind": "json",
        "produced_by": ["run-java-bff-loop", "resume-java-bff-loop"],
        "description": "Normalized Java BFF runner results for fake, provider, or Cline-bridge task execution.",
        "top_level_fields": [
            "generated_at",
            "bundle_id",
            "phase",
            "phase_pack_path",
            "context_pack_path",
            "response_text_path",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/merged/*/implementation_plan.json",
        "kind": "json",
        "produced_by": ["merge-java-bff-phases", "run-java-bff-loop"],
        "description": "Merged Java Spring Boot BFF implementation plan assembled from accepted phase reviews.",
        "top_level_fields": [
            "generated_at",
            "bundle_id",
            "entry_query_id",
            "status",
            "repository_plan",
            "bff_plan",
            "verification",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/skeletons/*/README.md",
        "kind": "markdown",
        "produced_by": ["generate-java-bff-skeleton", "run-java-bff-loop"],
        "description": "Generated Java Spring Boot skeleton bundle readme with implementation handoff guidance.",
        "top_level_fields": ["markdown document"],
    },
    {
        "path_pattern": "analysis/java_bff/skeletons/*/manifest.json",
        "kind": "json",
        "produced_by": ["generate-java-bff-skeleton", "run-java-bff-loop"],
        "description": "Generated Java Spring Boot skeleton manifest with bundle sources and emitted file list.",
        "top_level_fields": [
            "generated_at",
            "bundle_id",
            "base_package",
            "ready_for_skeletons",
            "source_artifacts",
            "files",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/loop/loop_state.json",
        "kind": "json",
        "produced_by": ["run-java-bff-loop", "resume-java-bff-loop"],
        "description": "Resumable Java BFF autonomous loop state for prompt execution, review, merge, and skeleton generation.",
        "top_level_fields": [
            "run_id",
            "status",
            "config",
            "current_prompt_json_path",
            "completed_prompts",
            "prompt_attempts",
            "merged_bundles",
            "skeleton_bundles",
            "iteration_count",
            "stop_reason",
            "last_error",
        ],
    },
    {
        "path_pattern": "analysis/java_bff/loop/completion_report.json",
        "kind": "json",
        "produced_by": ["run-java-bff-loop", "resume-java-bff-loop"],
        "description": "Terminal Java BFF loop status with merged-plan and skeleton completion tracking.",
        "top_level_fields": [
            "generated_at",
            "run_id",
            "status",
            "iterations",
            "stop_reason",
            "missing_artifacts",
            "completed_prompt_count",
            "merged_bundles",
            "skeleton_bundles",
            "last_error",
        ],
    },
]


def write_artifact_catalog(output_dir: Path) -> list:
    analysis_root = output_dir / "analysis" / "schema"
    analysis_root.mkdir(parents=True, exist_ok=True)
    json_path = analysis_root / "artifact_catalog.json"
    md_path = analysis_root / "artifact_catalog.md"
    payload = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "artifacts": ARTIFACT_SPECS,
    }
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(render_artifact_catalog_markdown(payload), encoding="utf-8")
    return [
        artifact_descriptor_for_path(json_path, "json", "Artifact catalog", "project"),
        artifact_descriptor_for_path(md_path, "markdown", "Artifact catalog (Markdown)", "project"),
    ]


def render_artifact_catalog_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Artifact Catalog",
        "",
        "Stable artifact contracts for the analyzer, self-healing workflow, and weak-LLM integration.",
        "",
    ]
    for item in payload["artifacts"]:
        lines.extend(
            [
                f"## {item['path_pattern']}",
                f"- Kind: `{item['kind']}`",
                f"- Produced by: {', '.join(f'`{command}`' for command in item['produced_by'])}",
                f"- Description: {item['description']}",
                f"- Top-level fields: {', '.join(f'`{field}`' for field in item['top_level_fields'])}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"
